package vn.io.litever.remind.core.designsystem.theme

import androidx.compose.ui.graphics.Color
import vn.io.litever.designsystem.theme.darkLiteverColors
import vn.io.litever.designsystem.theme.lightLiteverColors

val primaryLight = Color(0xFF8C4E28)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDBC9)
val onPrimaryContainerLight = Color(0xFF6F3813)
val secondaryLight = Color(0xFF765848)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBC9)
val onSecondaryContainerLight = Color(0xFF5C4131)
val tertiaryLight = Color(0xFF636032)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEAE5AB)
val onTertiaryContainerLight = Color(0xFF4B481D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xFFF4DED4)
val onSurfaceVariantLight = Color(0xFF52443C)
val outlineLight = Color(0xFF85746B)
val outlineVariantLight = Color(0xFFD7C2B8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E29)
val inverseOnSurfaceLight = Color(0xFFFFEDE5)
val inversePrimaryLight = Color(0xFFFFB68D)
val surfaceDimLight = Color(0xFFE8D7CF)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EB)
val surfaceContainerLight = Color(0xFFFCEAE3)
val surfaceContainerHighLight = Color(0xFFF6E5DD)
val surfaceContainerHighestLight = Color(0xFFF0DFD7)

val primaryLightMediumContrast = Color(0xFF5A2804)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF9E5D35)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF493022)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF866655)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF3A370E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF726F40)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F6)
val onBackgroundLightMediumContrast = Color(0xFF221A15)
val surfaceLightMediumContrast = Color(0xFFFFF8F6)
val onSurfaceLightMediumContrast = Color(0xFF170F0B)
val surfaceVariantLightMediumContrast = Color(0xFFF4DED4)
val onSurfaceVariantLightMediumContrast = Color(0xFF41332C)
val outlineLightMediumContrast = Color(0xFF5E4F48)
val outlineVariantLightMediumContrast = Color(0xFF7A6A61)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382E29)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE5)
val inversePrimaryLightMediumContrast = Color(0xFFFFB68D)
val surfaceDimLightMediumContrast = Color(0xFFD3C3BC)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1EB)
val surfaceContainerLightMediumContrast = Color(0xFFF6E5DD)
val surfaceContainerHighLightMediumContrast = Color(0xFFEAD9D2)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDFCEC7)

val primaryLightHighContrast = Color(0xFF4D1F00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF723A15)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3E2719)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5F4334)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF2F2D05)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF4D4B1F)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F6)
val onBackgroundLightHighContrast = Color(0xFF221A15)
val surfaceLightHighContrast = Color(0xFFFFF8F6)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF4DED4)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF362923)
val outlineVariantLightHighContrast = Color(0xFF55463F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF382E29)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFB68D)
val surfaceDimLightHighContrast = Color(0xFFC5B6AE)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F6)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFEDE5)
val surfaceContainerLightHighContrast = Color(0xFFF0DFD7)
val surfaceContainerHighLightHighContrast = Color(0xFFE2D1CA)
val surfaceContainerHighestLightHighContrast = Color(0xFFD3C3BC)

val primaryDark = Color(0xFFFFB68D)
val onPrimaryDark = Color(0xFF532200)
val primaryContainerDark = Color(0xFF6F3813)
val onPrimaryContainerDark = Color(0xFFFFDBC9)
val secondaryDark = Color(0xFFE6BEAA)
val onSecondaryDark = Color(0xFF432B1D)
val secondaryContainerDark = Color(0xFF5C4131)
val onSecondaryContainerDark = Color(0xFFFFDBC9)
val tertiaryDark = Color(0xFFCDC991)
val onTertiaryDark = Color(0xFF343208)
val tertiaryContainerDark = Color(0xFF4B481D)
val onTertiaryContainerDark = Color(0xFFEAE5AB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A120D)
val onBackgroundDark = Color(0xFFF0DFD7)
val surfaceDark = Color(0xFF1A120D)
val onSurfaceDark = Color(0xFFF0DFD7)
val surfaceVariantDark = Color(0xFF52443C)
val onSurfaceVariantDark = Color(0xFFD7C2B8)
val outlineDark = Color(0xFF9F8D84)
val outlineVariantDark = Color(0xFF52443C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD7)
val inverseOnSurfaceDark = Color(0xFF382E29)
val inversePrimaryDark = Color(0xFF8C4E28)
val surfaceDimDark = Color(0xFF1A120D)
val surfaceBrightDark = Color(0xFF413732)
val surfaceContainerLowestDark = Color(0xFF140D08)
val surfaceContainerLowDark = Color(0xFF221A15)
val surfaceContainerDark = Color(0xFF271E19)
val surfaceContainerHighDark = Color(0xFF312823)
val surfaceContainerHighestDark = Color(0xFF3D332E)

val primaryDarkMediumContrast = Color(0xFFFFD3BD)
val onPrimaryDarkMediumContrast = Color(0xFF421A00)
val primaryContainerDarkMediumContrast = Color(0xFFC87F55)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFDD4BF)
val onSecondaryDarkMediumContrast = Color(0xFF372013)
val secondaryContainerDarkMediumContrast = Color(0xFFAC8977)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFE3DFA5)
val onTertiaryDarkMediumContrast = Color(0xFF292701)
val tertiaryContainerDarkMediumContrast = Color(0xFF969360)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1A120D)
val onBackgroundDarkMediumContrast = Color(0xFFF0DFD7)
val surfaceDarkMediumContrast = Color(0xFF1A120D)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF52443C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFEED8CE)
val outlineDarkMediumContrast = Color(0xFFC2AEA4)
val outlineVariantDarkMediumContrast = Color(0xFF9F8D84)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF322823)
val inversePrimaryDarkMediumContrast = Color(0xFF713914)
val surfaceDimDarkMediumContrast = Color(0xFF1A120D)
val surfaceBrightDarkMediumContrast = Color(0xFF4D423D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0604)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241C17)
val surfaceContainerDarkMediumContrast = Color(0xFF2F2621)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A302B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF463B36)

val primaryDarkHighContrast = Color(0xFFFFECE4)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFB184)
val onPrimaryContainerDarkHighContrast = Color(0xFF190600)
val secondaryDarkHighContrast = Color(0xFFFFECE4)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE1BBA7)
val onSecondaryContainerDarkHighContrast = Color(0xFF180701)
val tertiaryDarkHighContrast = Color(0xFFF7F2B8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC9C58E)
val onTertiaryContainerDarkHighContrast = Color(0xFF0D0C00)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF1A120D)
val onBackgroundDarkHighContrast = Color(0xFFF0DFD7)
val surfaceDarkHighContrast = Color(0xFF1A120D)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF52443C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFFECE4)
val outlineVariantDarkHighContrast = Color(0xFFD3BEB5)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF0DFD7)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF713914)
val surfaceDimDarkHighContrast = Color(0xFF1A120D)
val surfaceBrightDarkHighContrast = Color(0xFF594E48)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF271E19)
val surfaceContainerDarkHighContrast = Color(0xFF382E29)
val surfaceContainerHighDarkHighContrast = Color(0xFF443934)
val surfaceContainerHighestDarkHighContrast = Color(0xFF50443F)

// ReMind Specific Colors mapped to the new colors
val remindLightColors = lightLiteverColors(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val remindDarkColors = darkLiteverColors(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
