package vn.io.litever.alarm.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Default Light Colors
val primaryLight = Color(0xFF825513)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDDB8)
val onPrimaryContainerLight = Color(0xFF653E00)
val secondaryLight = Color(0xFF715A41)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFCDDBD)
val onSecondaryContainerLight = Color(0xFF57432B)
val tertiaryLight = Color(0xFF54643D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD7E9B9)
val onTertiaryContainerLight = Color(0xFF3D4C28)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF211A13)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF211A13)
val surfaceVariantLight = Color(0xFFF1E0D0)
val onSurfaceVariantLight = Color(0xFF504539)
val outlineLight = Color(0xFF827568)
val outlineVariantLight = Color(0xFFD4C4B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F27)
val inverseOnSurfaceLight = Color(0xFFFCEEE2)
val inversePrimaryLight = Color(0xFFF8BB71)
val surfaceDimLight = Color(0xFFE5D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E5)
val surfaceContainerLight = Color(0xFFF9ECE0)
val surfaceContainerHighLight = Color(0xFFF3E6DA)
val surfaceContainerHighestLight = Color(0xFFEEE0D4)

// Logo Colors
val logo_up_light = Color(0xFF6B7280)
val logo_alarm_light = Color(0xFFF59E0B)

// Default Dark Colors
val primaryDark = Color(0xFFF8BB71)
val onPrimaryDark = Color(0xFF472A00)
val primaryContainerDark = Color(0xFF653E00)
val onPrimaryContainerDark = Color(0xFFFFDDB8)
val secondaryDark = Color(0xFFDFC2A2)
val onSecondaryDark = Color(0xFF3F2D17)
val secondaryContainerDark = Color(0xFF57432B)
val onSecondaryContainerDark = Color(0xFFFCDDBD)
val tertiaryDark = Color(0xFFBBCD9E)
val onTertiaryDark = Color(0xFF273513)
val tertiaryContainerDark = Color(0xFF3D4C28)
val onTertiaryContainerDark = Color(0xFFD7E9B9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF18120C)
val onBackgroundDark = Color(0xFFEEE0D4)
val surfaceDark = Color(0xFF18120C)
val onSurfaceDark = Color(0xFFEEE0D4)
val surfaceVariantDark = Color(0xFF504539)
val onSurfaceVariantDark = Color(0xFFD4C4B5)
val outlineDark = Color(0xFF9C8E80)
val outlineVariantDark = Color(0xFF504539)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEE0D4)
val inverseOnSurfaceDark = Color(0xFF372F27)
val inversePrimaryDark = Color(0xFF825513)
val surfaceDimDark = Color(0xFF18120C)
val surfaceBrightDark = Color(0xFF403830)
val surfaceContainerLowestDark = Color(0xFF130D07)
val surfaceContainerLowDark = Color(0xFF211A13)
val surfaceContainerDark = Color(0xFF251E17)
val surfaceContainerHighDark = Color(0xFF302921)
val surfaceContainerHighestDark = Color(0xFF3B332B)

val logo_up_dark = Color(0xFFCBD5E1)
val logo_alarm_dark = Color(0xFFFBBF24)
